name: producto-dev

services:
  mysql-producto-dev:
    image: mysql:8.4
    container_name: mysql-producto-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_producto
    ports:
      - "3391:3306"
    volumes:
      - mysql_producto_dev_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mysql_producto_dev_data:
