server:
  port: 7091

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: producto-route
              uri: lb://producto-service
              predicates:
                - Path=/api/productos/**
            - id: inventario-route
              uri: lb://inventario-service
              predicates:
                - Path=/api/inventarios/**
            - id: venta-route
              uri: lb://venta-service
              predicates:
                - Path=/api/ventas/**
            - id: pago-route
              uri: lb://pago-service
              predicates:
                - Path=/api/pagos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
