server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://${PRODUCTO_DB_HOST:mysql-producto}:${PRODUCTO_DB_PORT:3306}/${PRODUCTO_DB_NAME:db_producto}
    username: ${PRODUCTO_DB_USERNAME:root}
    password: ${PRODUCTO_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://registry-server:7081/eureka
